# Generated by Django 4.1.3 on 2022-12-14 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_customuser_profile_picture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="profile_picture",
            new_name="image",
        ),
    ]
