# Generated by Django 4.1.3 on 2022-12-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0016_delete_comment_alter_auctionhistory_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="category",
        ),
        migrations.RemoveField(
            model_name="item",
            name="img_url",
        ),
        migrations.AddField(
            model_name="item",
            name="finish_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
        migrations.DeleteModel(
            name="ItemCategory",
        ),
    ]
